### ISSUE TITLE
Make this repo more visible

### ISSUE THREAD

**Issue by ghost** [reiszner/Citation#1]
1) Add topics to this repo

2) Add "social preview" from repo settings

3) Also it says "this aircraft for 2020.4" but it works without problem. I wondered where can I download for 2020.3 and if it is not available can you make a release for 2020.3 ?

Like here: https://github.com/c172p-team/c172p/releases

**Comment by reiszner** [comment]
This is only the developement repo.
The Citation II is also in the default hangar, so you can download it via the launcher directly in FG.
You can use this developer version also in FG 2020.3, but the lights will not work properly, because
it uses exclusively Compositor lights.
Last changes that are not in the default hangar are the pushback and this is work in progress.
So if you use this version, hold in mind that pushback will not work.

**Comment by ghost** [comment]
Okay thank you I will download from default hangar.
